"""
This type stub file was generated by pyright.
"""

from .gmpy2 import *
from .gmpy2 import _C_API, __version__, _mpmath_create, _mpmath_normalize

def powmod(base: int, exp: int, mod: int) -> int: ...
